# Importing Libraries

In [7]:
import pandas as pd
import numpy as np
import os

## Importing Data

In [11]:
# creating path
path = r'C:\Users\smerg\esport_earning_2018-2023'

In [17]:
# importing data
GC = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'game_country_mapping.csv'), index_col=False)
CE = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'GeneralEsportData.csv'), index_col=False)
HE = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'HistoricalEsportData.csv'), index_col=False)

In [20]:
# Checking for missing or null values in each dataset
gc_missing = GC.isnull().sum()
ce_missing = CE.isnull().sum()
he_missing = HE.isnull().sum()

gc_missing, ce_missing, he_missing

(Game       0
 Country    0
 dtype: int64,
 Game                 0
 ReleaseDate          0
 Genre                0
 TotalEarnings        0
 OfflineEarnings      0
 PercentOffline      67
 TotalPlayers         0
 TotalTournaments     0
 dtype: int64,
 Date           0
 Game           0
 Earnings       0
 Players        0
 Tournaments    0
 dtype: int64)

In [26]:
# Step 1: Impute missing values in 'PercentOffline' with the median in general_esport_data_df (CE)
median_percent_offline = CE['PercentOffline'].median()
CE['PercentOffline'].fillna(median_percent_offline, inplace=True)

# Step 2: Standardize 'ReleaseDate' format in general_esport_data_df (CE)
CE['ReleaseDate'] = pd.to_datetime(CE['ReleaseDate'], errors='coerce', format='%Y')

# Step 3: Check for duplicates in all datasets
gc_duplicates = GC.duplicated().sum()
ce_duplicates = CE.duplicated().sum()
he_duplicates = HE.duplicated().sum()

# Removing duplicates if found
GC.drop_duplicates(inplace=True)
CE.drop_duplicates(inplace=True)
HE.drop_duplicates(inplace=True)

# Return the counts of duplicates found and handled
gc_duplicates, ce_duplicates, he_duplicates

C:\Users\smerg\AppData\Local\Temp\ipykernel_13000\2574747657.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  CE['PercentOffline'].fillna(median_percent_offline, inplace=True)

(0, 0, 0)

In [29]:
# Step 1: Merge 'game_country_mapping.csv' with 'GeneralEsportData.csv' on 'Game'
merged_gc_ce = pd.merge(CE, GC, on='Game', how='left')

# Step 2: Merge the result with 'HistoricalEsportData.csv' on 'Game'
merged_all = pd.merge(merged_gc_ce, HE, on='Game', how='left')

In [33]:
merged_all.head(100)
merged_all.tail(100)

,Game,ReleaseDate,Genre,TotalEarnings,OfflineEarnings,PercentOffline,TotalPlayers,TotalTournaments,Country,Date,Earnings,Players,Tournaments
9197,Gears of War 4,2016-01-01,Third-Person Shooter,3142785.00,3055000.00,0.972068,155,152,NaN,2019-06-01,1500.00,25.0,3.0
9198,Gears of War 4,2016-01-01,Third-Person Shooter,3142785.00,3055000.00,0.972068,155,152,NaN,2019-07-01,2500.00,31.0,5.0
9199,Gears of War 4,2016-01-01,Third-Person Shooter,3142785.00,3055000.00,0.972068,155,152,NaN,2019-08-01,1500.00,24.0,3.0
9200,Gears of War 4,2016-01-01,Third-Person Shooter,3142785.00,3055000.00,0.972068,155,152,NaN,2019-09-01,500.00,10.0,1.0
9201,Gears of War: Ultimate Edition,2015-01-01,Third-Person Shooter,170000.00,170000.00,1.000000,39,3,NaN,2016-01-01,60000.00,16.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9292,osu!,2007-01-01,Music / Rhythm Game,228205.84,26827.89,0.117560,854,205,NaN,2023-06-01,2564.33,26.0,2.0
9293,osu!,2007-01-01,Music / Rhythm Game,228205.84,26827.89,0.117560,854,205,NaN,2023-07-01,15370.71,44.0,8.0
9294,osu!,2007-01-01,Music / Rhythm Game,228205.84,26827.89,0.117560,854,205,NaN,2023-08-01,3009.95,9.0,3.0
9295,osu!,2007-01-01,Music / Rhythm Game,228205.84,26827.89,0.117560,854,205,NaN,2023-09-01,6278.93,119.0,7.0
9296,osu!,2007-01-01,Music / Rhythm Game,228205.84,26827.89,0.117560,854,205,NaN,2023-10-01,1228.14,6.0,2.0

In [37]:
merged_all.to_csv(os.path.join(path, '02 Data','Prepared Data', 'EsportsData.cvs'))

In [38]:
# Step 1: Review the structure of the dataset and its variables
data_overview = merged_all.info()

# Step 2: Perform basic descriptive statistical analysis (numeric columns)
descriptive_stats = merged_all.describe()

# Step 3: Check the distribution of categorical variables
categorical_distribution = merged_all.select_dtypes(include=['object']).nunique()

# Displaying the overview, descriptive statistics, and categorical distributions
data_overview, descriptive_stats, categorical_distribution

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9297 entries, 0 to 9296
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Game              9297 non-null   object
 1   ReleaseDate       9297 non-null   datetime64[ns]
 2   Genre             9297 non-null   object
 3   TotalEarnings     9297 non-null   float64
 4   OfflineEarnings   9297 non-null   float64
 5   PercentOffline    9297 non-null   float64
 6   TotalPlayers      9297 non-null   int64
 7   TotalTournaments  9297 non-null   int64
 8   Country           557 non-null    object
 9   Date              9244 non-null   object
 10  Earnings          9244 non-null   float64
 11  Players           9244 non-null   float64
 12  Tournaments       9244 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(4)
memory usage: 944.4+ KB

(None,
                          ReleaseDate  TotalEarnings  OfflineEarnings  \
 count                           9297   9.297000e+03     9.297000e+03
 mean   2010-10-04 11:56:03.020329216   1.655135e+07     1.227973e+07
 min              1981-01-01 00:00:00   0.000000e+00     0.000000e+00
 25%              2007-01-01 00:00:00   1.307260e+05     7.620212e+04
 50%              2012-01-01 00:00:00   1.300330e+06     6.561308e+05
 75%              2016-01-01 00:00:00   6.590063e+06     5.081389e+06
 max              2023-01-01 00:00:00   3.371080e+08     2.982906e+08
 std                              NaN   4.978746e+07     4.087311e+07

        PercentOffline  TotalPlayers  TotalTournaments      Earnings  \
 count     9297.000000   9297.000000       9297.000000  9.244000e+03
 mean         0.707792   1272.726256        680.107346  1.796551e+05
 min          0.000000      0.000000          0.000000  0.000000e+00
 25%          0.528844    108.000000         39.000000  1.075000e+03
 50%          0.851000    346.000000        156.000000  1.026800e+04
 75%          0.966042   1283.000000        543.000000  7.150557e+04
 max          1.000000  16272.000000       7245.000000  4.013865e+07
 std          0.309309   2499.066915       1384.251334  1.017222e+06

            Players  Tournaments
 count  9244.000000  9244.000000
 mean     59.721874     6.633600
 min       0.000000     1.000000
 25%       6.000000     1.000000
 50%      16.000000     2.000000
 75%      51.000000     6.000000
 max    1719.000000   172.000000
 std     130.098551    12.098553  ,
 Game       650
 Genre       12
 Country      3
 Date       297
 dtype: int64)